RUN_STRINGS = (
    "Menurutmu kemana kamu akan pergi?",
    "Hah? Apa? Apakah mereka lolos?",
    "ZZzzZZzz ... Hah? Apa? Oh, hanya mereka lagi, lupakan.",
    "Kembali kesini!",
    "Tidak terlalu cepat ...",
    "Awas ke dinding!",
    "Jangan tinggalkan aku sendiri dengan mereka !!",
    "Kamu lari, kamu mati.",
    "Bercanda, aku ada dimana-mana",
    "Kamu akan menyesali itu ...",
    "Kamu juga bisa mencoba /punchme, kudengar itu menyenangkan.",
    "Ganggu orang lain, tidak ada yang peduli.",
    "Kamu bisa lari, tapi kamu tidak bisa bersembunyi.",
    "Apakah hanya itu yang kamu punya?",
    "Saya di belakang Anda...",
    "Anda punya teman!",
    "Kita bisa melakukan ini dengan cara mudah, atau cara sulit.",
    "Anda tidak mengerti, bukan?",
    "Ya, sebaiknya kau lari!",
    "Tolong, ingatkan saya betapa saya peduli?",
    "Aku akan berlari lebih cepat jika jadi kamu.",
    "Itu pasti droid yang kami cari.",
    "Semoga peluang selalu menguntungkan Anda.",
    "Kata-kata terakhir yang terkenal.",
    "Dan mereka menghilang selamanya, tidak pernah terlihat lagi.",
    "Oh, lihat aku! Saya sangat keren, saya bisa lari dari bot!",
    "Ya ya, cukup ketuk /punchme",
    "Ini, ambil cincin ini dan pergilah ke Mordor saat kamu melakukannya.",
    "Legenda mengatakan, mereka masih berjalan ...",
    "Tidak seperti Harry Potter, orang tuamu tidak bisa melindungimu dariku.",
    "Ketakutan menyebabkan kemarahan. Kemarahan mengarah pada kebencian. Kebencian menyebabkan penderitaan. Jika Anda terus berlari dalam ketakutan, Anda mungkin"
    "jadilah Vader berikutnya.",
    "Beberapa kalkulasi nanti, saya telah memutuskan minat saya pada kejahatan Anda tepat 0.",
    "Legenda mengatakan, mereka masih berjalan.",
    "Teruskan, kami tidak yakin kami menginginkanmu di sini.",
    "Kamu seorang penyihir- Oh. Tunggu. Kamu bukan Harry, teruslah bergerak.",
    "TIDAK BERLARI DI HALLWAYS!",
    "Hasta la vista, sayang.",
    "Siapa yang membiarkan anjing keluar?",
    "Ini lucu, karena tidak ada yang peduli.",
    "Ah, sayang sekali. Aku suka yang itu.",
    "Terus terang, sayangku, aku tidak peduli.",
    "Milkshake saya membawa semua anak laki-laki ke halaman ... Jadi lari lebih cepat!",
    "Anda tidak bisa MENANGANI kebenaran!",
    "Dahulu kala, di galaksi yang sangat jauh ... Seseorang akan peduli tentang itu. Tapi sekarang tidak lagi.",
    "Hei, lihat mereka! Mereka lari dari palu yang tak terelakkan ... Manis.",
    "Han menembak lebih dulu. Aku juga.",
    "Apa yang kamu kejar, kelinci putih?",
    "Seperti yang dikatakan si manis ... LARI!",
)

SLAP_stella_TEMPLATES = (
    "Jika kau menamparku sekali lagi, Feri akan membunuhmu.",
    "Anak Kampang.",
    [
        "Saya membungkam Anda Sebentar.", #normal reply
        "Berhenti menamparku, kau tahu siapa pemilikku 😅", #reply to admin
        "tmute" #command
    ]
)

SLAP_TEMPLATES = (
    "{user2} Di Tembak Mati Oleh Si {user1}.",
    "{user2} Membungkukkan Kepalanya Kepada Si {user1}.",
    "{user2} Mencium Bibir {user1} Karena Gak Bisa Tahan Nafsu.",
    "{user2} Menjilat Biji Si {user1}.",
    "{user1} Membunuh {user2} Dengan Golok Milik Bapaknya.",
    "{user2} Mampus Kau Mati Aja Wkwk.",
    "{user2} Sebenarnya Adalah Babu Dari {user1}.",
    "{user1} Membawa {user2} Ke Semak-Semak Rimbun.",
    "{user1} Sebenarnya Menyukai Dan Mencintai {user2}.",
    "{user1} Membawa Kabur {user2} Untuk Menjalani Kawin Lari.",
    "{user2} Tidak Sengaja Terjatuh Lalu Memeluk Dan Mencium Bibir {user1}.",
    "{user1} Menghantam Kepala {user2} Dengan Kayu Dan Besi.",
    "{user1} Membawa Kabur {user2} Untuk Ena Ena Di Kamar.",
    "{user2} Selalu Di Buly Oleh {user1}.",
    "{user2} Adalah Contoh Didikan Sesat Dari {user1}.",
    "{user2} Suka Mengintip Tante-Tante Yang Sedang Mandi.",
    "{user1} Croot Didalam {user2}.",
    "{user2} Terbakar Sampai Mati.",
    "{user2} Sibakar Sampai Garing Saat Bertarung {user1}.",
    "{user2} Tewas Tersambar Petir, Duar Me**k",
    "{user2} Menusbol {user1} Dengan Kecepatan Yang Mengagumkan.",
    "{user1} {hits} {user2} Dengan Batu!.",
    "{user1} {hits} {user2} Dengan Sodokan!.",
    "{user1} {hits} {user2} Dengan Bola!.",    
    "{user1} {hits} {user2} Dengan Tangan Kosong!.",
    "{user1} Dan {user2} Suka Mencabuli Loli!.",
    "{user1} Di Entot Oleh {user2}.",
    "{user1} Dan {user2} Selalu Kena Masalah.",
    "{user1} Mengecrottt {user2} Dengan Laser Bol...Bbbbbb*",
    "{user1} Ara Ara's {user2}.",
    "{user1} Ora Ora's {user2}.",
)

PING_STRING = (
    "PONG!!",
    "Aku Disini!",
)

ITEMS = (
    "wajan besi cor",
    "meong marah",
    "Anunya Sandy",
    "tongkat kayu",
    "sekop",
    "pemanggang roti",
    "Book",
    "laptop",
    "ayam karet",
    "Kolor Ehsan",
    "batu berat",
    "kotoran Babi",
    "banyak batu bata",
    "rasengan",
    "Kepala Tata",
    "Celana dalam Risman",
    "rasenshuriken",
    "Murasame",
    "melarang",
    "chunchunmaru",
    "Pantat apis",
    "rasengan",
    "Celana dalam piki",
)

THROW = (
    "throws",
    "flings",
    "chucks",
    "hurls",
)

HIT = (
    "hits",
    "whacks",
    "slaps",
    "smacks",
    "bashes",
    "pats",

)

ABUSE_STRINGS = (
    "Fuck off",
    "Stfu go fuck yourself",
    "Ur mum gey",
    "Ur dad lesbo",
    "Bsdk",
    "Nigga",
    "Ur granny tranny",
    "you noob",
    "Relax your Rear,ders nothing to fear,The Rape train is finally here",
    "Stfu bc",
    "Stfu and Gtfo U nub",
    "GTFO bsdk",
    "CUnt",
    " Gay is here",
    "Ur dad gey bc ",
)

EYES = [
    ['⌐■', '■'],
    [' ͠°', ' °'],
    ['⇀', '↼'],
    ['´• ', ' •`'],
    ['´', '`'],
    ['`', '´'],
    ['ó', 'ò'],
    ['ò', 'ó'],
    ['⸌', '⸍'],
    ['>', '<'],
    ['Ƹ̵̡', 'Ʒ'],
    ['ᗒ', 'ᗕ'],
    ['⟃', '⟄'],
    ['⪧', '⪦'],
    ['⪦', '⪧'],
    ['⪩', '⪨'],
    ['⪨', '⪩'],
    ['⪰', '⪯'],
    ['⫑', '⫒'],
    ['⨴', '⨵'],
    ['⩿', '⪀'],
    ['⩾', '⩽'],
    ['⩺', '⩹'],
    ['⩹', '⩺'],
    ['◥▶', '◀◤'],
    ['◍', '◎'],
    ['/͠-', '┐͡-\\'],
    ['⌣', '⌣”'],
    [' ͡⎚', ' ͡⎚'],
    ['≋'],
    ['૦ઁ'],
    ['  ͯ'],
    ['  ͌'],
    ['ළ'],
    ['◉'],
    ['☉'],
    ['・'],
    ['▰'],
    ['ᵔ'],
    [' ﾟ'],
    ['□'],
    ['☼'],
    ['*'],
    ['`'],
    ['⚆'],
    ['⊜'],
    ['>'],
    ['❍'],
    ['￣'],
    ['─'],
    ['✿'],
    ['•'],
    ['T'],
    ['^'],
    ['ⱺ'],
    ['@'],
    ['ȍ'],
    ['  '],
    ['  '],
    ['x'],
    ['-'],
    ['$'],
    ['Ȍ'],
    ['ʘ'],
    ['Ꝋ'],
    [''],
    ['⸟'],
    ['๏'],
    ['ⴲ'],
    ['◕'],
    ['◔'],
    ['✧'],
    ['■'],
    ['♥'],
    [' ͡°'],
    ['¬'],
    [' º '],
    ['⨶'],
    ['⨱'],
    ['⏓'],
    ['⏒'],
    ['⍜'],
    ['⍤'],
    ['ᚖ'],
    ['ᴗ'],
    ['ಠ'],
    ['σ'],
    ['☯']
]

MOUTHS = [
    ['v'],
    ['ᴥ'],
    ['ᗝ'],
    ['Ѡ'],
    ['ᗜ'],
    ['Ꮂ'],
    ['ᨓ'],
    ['ᨎ'],
    ['ヮ'],
    ['╭͜ʖ╮'],
    [' ͟ل͜'],
    [' ͜ʖ'],
    [' ͟ʖ'],
    [' ʖ̯'],
    ['ω'],
    [' ³'],
    [' ε '],
    ['﹏'],
    ['□'],
    ['ل͜'],
    ['‿'],
    ['╭╮'],
    ['‿‿'],
    ['▾'],
    ['‸'],
    ['Д'],
    ['∀'],
    ['!'],
    ['人'],
    ['.'],
    ['ロ'],
    ['_'],
    ['෴'],
    ['ѽ'],
    ['ഌ'],
    ['⏠'],
    ['⏏'],
    ['⍊'],
    ['⍘'],
    ['ツ'],
    ['益'],
    ['╭∩╮'],
    ['Ĺ̯'],
    ['◡'],
    [' ͜つ']
]

EARS = [
    ['q', 'p'],
    ['ʢ', 'ʡ'],
    ['⸮', '?'],
    ['ʕ', 'ʔ'],
    ['ᖗ', 'ᖘ'],
    ['ᕦ', 'ᕥ'],
    ['ᕦ(', ')ᕥ'],
    ['ᕙ(', ')ᕗ'],
    ['ᘳ', 'ᘰ'],
    ['ᕮ', 'ᕭ'],
    ['ᕳ', 'ᕲ'],
    ['(', ')'],
    ['[', ']'],
    ['¯\\_', '_/¯'],
    ['୧', '୨'],
    ['୨', '୧'],
    ['⤜(', ')⤏'],
    ['☞', '☞'],
    ['ᑫ', 'ᑷ'],
    ['ᑴ', 'ᑷ'],
    ['ヽ(', ')ﾉ'],
    ['\\(', ')/'],
    ['乁(', ')ㄏ'],
    ['└[', ']┘'],
    ['(づ', ')づ'],
    ['(ง', ')ง'],
    ['⎝', '⎠'],
    ['ლ(', 'ლ)'],
    ['ᕕ(', ')ᕗ'],
    ['(∩', ')⊃━☆ﾟ.*'],
]

TOSS = (
    "Heads",
    "Tails",
)

DECIDE = (
    "Yes.",
    "NoU.",
    "Maybe."
)

TABLE = (
    "(╯°□°）╯彡 ┻━┻",
    "I ran out of tables, will order more.",
    "Go do some work instead of flippin tables."
)
